# Use the official Python base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /

# Install libgl1-mesa-glx for libGL.so.1
RUN apt-get update && apt-get install -y libgl1-mesa-glx

# Copy the requirements.txt file into the container
COPY requirements.txt requirements.txt

# Install the dependencies individually to ignore errors
RUN pip install --no-cache-dir pip==23.0.1 \
    && while IFS= read -r pkg || [ -n "$pkg" ]; do \
        pip install --no-cache-dir "$pkg" || echo "Failed to install $pkg" >&2; \
    done < requirements.txt
RUN apt-get update && \
apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6


# Copy the rest of the application code into the container
COPY . .

# Expose the port that the Flask app runs on
EXPOSE 5000

# Define the command to run the application
CMD ["python", "app.py"]
